FROM node:latest
WORKDIR /usr/src/app
COPY package*.json ./
RUN apt update
COPY . .
RUN npm i -g @adonisjs/cli
COPY . .
RUN	npm install
COPY . .
RUN	apt install nano
COPY . .
EXPOSE 3333
CMD [ "node", "server.js" ]